//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPriceListingGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string EXCEL_COLUMN_PRODUCT_NO {
            get {
                return ((string)(this["EXCEL_COLUMN_PRODUCT_NO"]));
            }
            set {
                this["EXCEL_COLUMN_PRODUCT_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string EXCEL_COLUMN_PRODUCT_NAME_EN {
            get {
                return ((string)(this["EXCEL_COLUMN_PRODUCT_NAME_EN"]));
            }
            set {
                this["EXCEL_COLUMN_PRODUCT_NAME_EN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string EXCEL_COLUMN_PRODUCT_NAME_KH {
            get {
                return ((string)(this["EXCEL_COLUMN_PRODUCT_NAME_KH"]));
            }
            set {
                this["EXCEL_COLUMN_PRODUCT_NAME_KH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string EXCEL_COLUMN_PRODUCT_UNIT_NAME {
            get {
                return ((string)(this["EXCEL_COLUMN_PRODUCT_UNIT_NAME"]));
            }
            set {
                this["EXCEL_COLUMN_PRODUCT_UNIT_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string EXCEL_COLUMN_PRODUCT_SALE_PRICE {
            get {
                return ((string)(this["EXCEL_COLUMN_PRODUCT_SALE_PRICE"]));
            }
            set {
                this["EXCEL_COLUMN_PRODUCT_SALE_PRICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int EXCEL_START {
            get {
                return ((int)(this["EXCEL_START"]));
            }
            set {
                this["EXCEL_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int EXCEL_END {
            get {
                return ((int)(this["EXCEL_END"]));
            }
            set {
                this["EXCEL_END"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_PREVIEW {
            get {
                return ((bool)(this["AUTO_PREVIEW"]));
            }
            set {
                this["AUTO_PREVIEW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string EXCEL_COLUMN_CATEGORY_EN {
            get {
                return ((string)(this["EXCEL_COLUMN_CATEGORY_EN"]));
            }
            set {
                this["EXCEL_COLUMN_CATEGORY_EN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public string EXCEL_COLUMN_CATEGORY_KH {
            get {
                return ((string)(this["EXCEL_COLUMN_CATEGORY_KH"]));
            }
            set {
                this["EXCEL_COLUMN_CATEGORY_KH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("រ")]
        public string CURRENCY_SYMBOL {
            get {
                return ((string)(this["CURRENCY_SYMBOL"]));
            }
            set {
                this["CURRENCY_SYMBOL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("png")]
        public string IMAGE_EXTENSION {
            get {
                return ((string)(this["IMAGE_EXTENSION"]));
            }
            set {
                this["IMAGE_EXTENSION"] = value;
            }
        }
    }
}
